name = "Additive"
author = "SkywardMC"
version = "1.35.0+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "69d5f974df552d828511ed99303c676ac1f9082ec1cb27da2fabae88dfa79d74"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"
