name = "Additive"
author = "SkywardMC"
version = "1.35.0+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12552fd1d4c4309448a97b307dd31c0e83371ec8aa5845bf7f958a4c8335dbcd"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
